### ISSUE TITLE
Inverted UVs on export

### ISSUE THREAD

**Issue by rasteron** [plepers/AwayExtensions-FBXPlugin#2]
Hi, I got to build the exporter with VS2015 but got some issues with inverted UVs when loading and viewing it with Prefab3D. Any ideas?

**Comment by plepers** [comment]
Texture coordinates are exported 'as-is' from FBX file.

Maybe the software exporting the fbx consider UV 0,0 in the top-left corner, and Prefab to be the bottom left corner. (or vice versa)

http://stackoverflow.com/questions/11861336/opengl-es-render-to-textture-appears-upside-down/11863857#11863857

**Comment by rasteron** [comment]
Thanks. Actually it's a ready to use Mixamo model with just one animation which you can download freely on their site. Here's a copy maybe you can check if it's just my build. https://drive.google.com/open?id=0B9v28NqJWRrnb2Q5eDdPM3IyTVk

or do you have any recommended pipeline/software to get the right UV for the exporter?

**Comment by plepers** [comment]
There is many solutions:
   - flip the UVS in the source FBX (with any 3D software)
   - flip the UVS in the AWD with some tools (https://github.com/plepers/awd-js/blob/master/src/tools/flipUvsY.js)
   - preprocess your assets to flip the textures (It's what i do generally, with imagemagick -flip option)
   - in webgl you have command to flip texture at runtime (UNPACK_FLIP_Y_WEBGL)

**Comment by rasteron** [comment]
Ok thanks for the info!
